# Generated by Django 2.2.5 on 2019-09-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodash',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
